### ISSUE TITLE
Is this plugin must be registered globally?

### ISSUE THREAD

**Issue by wwwossai** [highlightjs/vue-plugin#10]
i read the [docs for vue2](https://github.com/highlightjs/vue-plugin/tree/1-stable), and can't find the locally regisered example, only the globally registered example. so i try it out, and failed. So is this plugin can only be registered globablly, or am i miss something? 

i read the issue #1 , it seems related, but i'm using one single version of highlightjs 10.7.2, so i'm not quite clear whether or not this plugin supports locally register.

thanks.

NODE_MODULES
```

+---@highlightjs
|   \---vue-plugin
|       +---dist
|       \---src
|           \---lib
+---highlight.js
|   +---lib
|   |   \---languages
|   +---scss
|   +---styles
|   \---types
```

![image](https://user-images.githubusercontent.com/77321546/122493988-3366c680-d01b-11eb-9f7f-c160e288b045.png)

GOOD version (Globally registered）: 

![image](https://user-images.githubusercontent.com/77321546/122492752-eda8fe80-d018-11eb-819c-0e2212a7038a.png)

```html
<template>
  <div>
    <highlightjs language="javascript" code="var x = 5;" />
  </div>
</template>

<script>
import Vue from 'vue'
import hljs from 'highlight.js/lib/core'
import javascript from 'highlight.js/lib/languages/javascript'
import 'highlight.js/styles/a11y-dark.css'

import hljsVuePlugin from '@highlightjs/vue-plugin'

hljs.registerLanguage('javascript', javascript)
Vue.use(hljsVuePlugin)
export default {
  components: {}
}
</script>
```

BAD version (Registered in single file component）:

![image](https://user-images.githubusercontent.com/77321546/122493092-a8d19780-d019-11eb-9a20-ed4f2c3e3050.png)

```html
<template>
  <div>
    <highlightjs language="javascript" code="var x = 5;" />
  </div>
</template>

<script>
import Vue from 'vue'
import hljs from 'highlight.js/lib/core'
import javascript from 'highlight.js/lib/languages/javascript'
import 'highlight.js/styles/a11y-dark.css'

import hljsVuePlugin from '@highlightjs/vue-plugin'

hljs.registerLanguage('javascript', javascript)
// Vue.use(hljsVuePlugin)
export default {
  components: { hljsVuePlugin }
}
</script>
```

errors in chrome console: 
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <highlightjs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <TestTarget> at src/views/WebView/SourceCodeViewer.vue
       <TestPage> at src/pages/TestPage.vue
         <App> at src/App.vue
           <Root>
```

if i give a name，the error message change, but still cannot render the 'var x = 5' 
```
export default {
  components: { 'highlightjs': hljsVuePlugin }
}
```

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Highlightjs>
       <TestTarget> at src/views/WebView/SourceCodeViewer.vue
         <TestPage> at src/pages/TestPage.vue
           <App> at src/App.vue
             <Root>
```

**Comment by wwwossai** [comment]
it seems that the project name 'vue-plugin' already indicate that this is a vue plugin not component, which can only be installed using Vue.use and use global registration, according to the vue.js docs [here](https://vuejs.org/v2/guide/plugins.html)。

**Comment by joshgoebel** [comment]
The vue2 version exports component also, though Vue 3 version doe now.  Perhaps that would work?

```
export default {
  components: { 'highlightjs': hljsVuePlugin.component }
}
```

**Comment by wwwossai** [comment]
@joshgoebel yes it works! thanks for the help~~

**Comment by joshgoebel** [comment]
@Trinovantes Is there a reason this export was removed from the Vue 3 version?

**Comment by Trinovantes** [comment]
Just an oversight on my part. It should be fine to export for a local component

**Comment by joshgoebel** [comment]
Would mind resolving maybe? 🙃
