### ISSUE TITLE
LineNumbers

### ISSUE THREAD

**Issue by Hunlongyu** [highlightjs/vue-plugin#14]
Does the plug-in support displaying the number of rows? Will it be supported in the future?

![image](https://user-images.githubusercontent.com/15273630/131332185-6bda7e16-e373-4435-8bea-4b7e1af1d389.png)

**Comment by joshgoebel** [comment]
Unlikely, given our thoughts on [line numbers](https://highlightjs.readthedocs.io/en/latest/line-numbers.html), but using a line numbers plugin side-by-side with this plugin should be possible.
