### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by duansheli** [highlightjs/vue-plugin#2]
`Vue.use(vuePlugin); ` is vue 2.x
can this use with vue 3.x

**Comment by joshgoebel** [comment]
No idea.  It was definitely written with v2 in mind.

**Comment by joshgoebel** [comment]
If someone from the Vue community would like to look at that it might take to support Vue 3 that'd be awesome.

**Comment by joshgoebel** [comment]
Resolved via #3.
