### ISSUE TITLE
How to use hljsVuePlugin in unit test w/ vitest + @testing-library/vue ?

### ISSUE THREAD

**Issue by smarlhens** [highlightjs/vue-plugin#30]
### Describe the bug

Hi there 👋🏻 ,

I'm currently using this plugin in my `Vue 3` + `vite` + `vitest` + `@testing-library/vue` project and I'm facing an issue when trying to run my test:
![image](https://user-images.githubusercontent.com/11817371/168617132-d57538e7-6821-4e5d-bb47-9ef8bcf7c27b.png)

I'm not sure if the error comes from your library, but maybe from my code or from my test implementation. If this is the case I apologize in advance.

Could you help me to solve this problem?

### Reproduction

I've created a repo with one test case:
- ❌ simple component using `highlightjs` component

I'm declaring hljsVuePlugin as a `global.plugins` follwing what I've understood from [`@vue/test-utils` documentation](https://test-utils.vuejs.org/api/#global-plugins) but I do not know how to provide Vue instance 🤔 

Repro repository : [smarlhens/vue-vite-vitest-highlightjs-vue-plugin](https://github.com/smarlhens/vue-vite-vitest-highlightjs-vue-plugin)

**Comment by Trinovantes** [comment]
Looks like you're trying to import the IIFE module instead of the ESM module. Try explicitly aliasing `@highlightjs/vue-plugin` to `@highlightjs/vue-plugin/dist/highlightjs-vue.min.js`

**Comment by smarlhens** [comment]
Test is working fine using `import hljsVuePlugin from '@highlightjs/vue-plugin/dist/highlightjs-vue.esm.min.js';` but this is more like a workaround than a proper solution. 

It's look like `vitest` (cf. [vitest!747](https://github.com/vitest-dev/vitest/issues/747): https://github.com/vitest-dev/vitest/issues/747#issuecomment-1038742861 & https://github.com/vitest-dev/vitest/issues/747#issuecomment-1038915678) is using `import` field to import libraries we use native import. And node doesn't understand `module` field, so I've tried adding following code to your [`package.json`](https://github.com/highlightjs/vue-plugin/blob/71cbe56c935e93c29337998aa7ef9ab58946cded/package.json) and it's seems to be working fine: 
```json
  "exports": {
    ".": {
      "import": "./dist/highlightjs-vue.esm.min.js",
      "require": "./dist/highlightjs-vue.min.js"
    }
  },
```
This kind of change can lead to breaking changes (cf. [node: package-entry-points](https://nodejs.org/api/packages.html#package-entry-points)) as `exports` is overriding `main` declaration in `package.json`.

I guess you are better suited to defined if this change is possible or not in your codebase. I let you investigate on this subject, I will be glad to help but I'm not sure I have all the knowledge needed.

**Comment by smarlhens** [comment]
Looks like someone else have propose a MR to fix https://github.com/highlightjs/vue-plugin/pull/27 👀

**Comment by smarlhens** [comment]
Looks like someone else have propose a MR to fix https://github.com/highlightjs/vue-plugin/pull/27 👀

**Comment by smarlhens** [comment]
@joshgoebel are you planning to publish a new release that will contain #27 merged code ?

**Comment by joshgoebel** [comment]
Sorry for delay.  Just tried this now but npm is being stupid... denied my OTP and now it's refusing to `publish` with `npm ERR! Cannot convert undefined or null to object`... I'll circle back tomorrow and see if I have better luck.

**Comment by joshgoebel** [comment]
2.1.1 published.
