### ISSUE TITLE
How do I change the theme on the fly?

### ISSUE THREAD

**Issue by Artawower** [highlightjs/vue-plugin#31]
Hello, how can I change the theme on the fly? When I change the dark mode on the site, I would like to choose a black theme, and vice versa.

**Comment by joshgoebel** [comment]
Theming is all just what CSS you have loaded, so you'd have to write JS to load/switch out different CSS on the fly if that's the desire.

You could look at the Highlight.js demo for just one way to do this:

https://highlightjs.org/static/demo/

**Comment by Artawower** [comment]
Thanks, solved
