### ISSUE TITLE
Missing install instructions on README.md

### ISSUE THREAD

**Issue by sistematico** [highlightjs/vue-plugin#37]
Missing name of package in README.md:
`npm install @highlightjs/vue-plugin` or `pnpm add @highlightjs/vue-plugin`

Thank you.

**Comment by beatreichenbach** [comment]
+1
Please add this to the readme.

**Comment by joshgoebel** [comment]
PR is welcome!

**Comment by beatreichenbach** [comment]
Done! https://github.com/highlightjs/vue-plugin/pull/51
