### ISSUE TITLE
Providing a language doesn't disable autodetect

### ISSUE THREAD

**Issue by barrycohen** [highlightjs/vue-plugin#41]
The following does not use shell highlighting:

```html
<highlightjs language="shell" code="#include <iostream>"></highlightjs>
```

Instead, it autodetects cpp and uses that, even though "shell" was explicitly provided. It is possible to force autodetect off but I don't think that's supposed to be required:

```html
<highlightjs :autodetect="false" language="shell" code="#include <iostream>"></highlightjs>
```

See this fiddle https://jsfiddle.net/5nvhra3p/ for a live example.

I think there's a logic error in `vue.ts`:

```js
const autodetect = computed(() => props.autodetect || !language.value)
```

I think this should be:

```js
const autodetect = computed(() => props.autodetect && !language.value)
```

**Comment by joshgoebel** [comment]
I think you may be right, could you test and make a PR perhaps?
