### ISSUE TITLE
Does the plugin support vite v3.1.9?

### ISSUE THREAD

**Issue by libsgh** [highlightjs/vue-plugin#43]
Dev works fine, but when i use `vite build`, and`vite preview`, it doesn't show any style, and no error output.
```
import 'highlight.js/styles/atom-one-light.css'
import 'highlight.js/lib/common'
import hljsVuePlugin from "@highlightjs/vue-plugin"
export default({
  name: "code",
  components:{
    highlightjs: hljsVuePlugin.component
  }
})
```
![image](https://user-images.githubusercontent.com/25656088/210310892-9033587a-c480-4c44-9614-355bf7aea1b2.png)

**Comment by xiaomaiyun** [comment]
https://github.com/highlightjs/vue-plugin/issues/38#issuecomment-1356383004

**Comment by xiaomaiyun** [comment]
I have temporarily solved this problem. The reason is that webpack did not pack the unused code when packing, so quotes it here.

```
import 'highlight.js/styles/atom-one-dark.css'
import hljsCommon from 'highlight.js/lib/common'
import hljsVuePlugin from '@highlightjs/vue-plugin'
. . . 
const app = createApp(App)
. . .
// 注意：解决Vue使用highlight.js build打包发布后样式消失问题，原因是webpack在打包的时候没有把未被使用的代码打包进去，因此，在此处引用一下，看似无意义实则有用
hljsCommon.highlightAuto('<h1>Highlight.js has been registered successfully!</h1>').value
app.use(hljsVuePlugin)
. . .
```

**Comment by joshgoebel** [comment]
I wonder if `import hljs from 'highlight.js/lib/common'` would work?

**Comment by xiaomaiyun** [comment]
> hljsCommon.highlightAuto('<h1>Highlight.js has been registered successfully!</h1>').value

work,if this code

**Comment by xiaomaiyun** [comment]
> I wonder if `import hljs from 'highlight.js/lib/common'` would work?

`hljsCommon.highlightAuto('<h1>Highlight.js has been registered successfully!</h1>').value`

work,if this code

**Comment by libsgh** [comment]
> > I wonder if `import hljs from 'highlight.js/lib/common'` would work?
> 
> `hljsCommon.highlightAuto('<h1>Highlight.js has been registered successfully!</h1>').value`
> 
> work,if this code

It's work for me, thanks.
