### ISSUE TITLE
`language` setting is not effective.

### ISSUE THREAD

**Issue by yamanoku** [highlightjs/vue-plugin#8]
I have specified `highlightjs/vue-plugin` from the one created in the Vue-cli template.
https://codesandbox.io/s/bold-glitter-fl0e6?file=/src/main.js

However, even though I have specified the corresponding language in `registerLanguage` as per the [README](https://github.com/highlightjs/vue-plugin#using-es6-modules--bundling), the style is not reflected.

<img width="669" alt="" src="https://user-images.githubusercontent.com/1996642/120464595-12299780-c3d8-11eb-976a-632edec429aa.png">

<img width="526" alt="The language 'javascript' you specified could not be found" src="https://user-images.githubusercontent.com/1996642/120465256-bb708d80-c3d8-11eb-83b1-745c9134b88c.png">

https://fl0e6.csb.app/

---
highlightjs/vue-plugin version: latest

**Comment by joshgoebel** [comment]
Does your project have two different HLJS versions in it's dependency tree?

https://github.com/highlightjs/vue-plugin/issues/1

**Comment by wwwossai** [comment]
@yamanoku manually reinstall the highlight.js@10.7.2（not latest) and it works.

`npm i highlight.js@10.7.2`

![image](https://user-images.githubusercontent.com/77321546/122390887-0bd51700-cfa5-11eb-8a21-b578e3650c5a.png)

**Comment by yamanoku** [comment]
That's true, but I want to be able to use the latest version.
I created this issue because I thought I could use this plugin with the latest version of highlight.js.

**Comment by joshgoebel** [comment]
Right now it's not possible to have two different versions in your dependency tree.  Closing this as a dup of #1.

**Comment by alonesuperman** [comment]
https://github.com/highlightjs/vue-plugin/blob/454575aef428cdfe164156f2451cf3aecea7f74e/src/vue.ts#L25

it should be

```typescript
const language = toRef(props, "language")
```
