### ISSUE TITLE
Use the new API

### ISSUE THREAD

**Issue by Ian321** [highlightjs/vue-plugin#9]
Replace the function call with the [improved API](https://github.com/highlightjs/highlight.js/issues/2277).

It currently logs the following:
```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

**Comment by joshgoebel** [comment]
Old version? https://github.com/highlightjs/vue-plugin/commit/3785c415061ef41296210f6c06fe51620b86cd52

**Comment by Ian321** [comment]
Yea I noticed that a bit too late and closed the issue.
